apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bff-deploy
  namespace: efsoft
  labels:
    app:  efsoft-bff
spec:
  selector:
    matchLabels:
      app: efsoft-bff
  #replicas: 1
  template:
    metadata:
      labels:
        app:  efsoft-bff
    spec:
      containers:
      - name:  efsoft-bff
        image:  emilfilip/efsoft_bff:4
        env:
        - name: CustomersService__CustomersServiceBaseAddress  # Set the service name for Microservice B
          value: "http://customers-svc:8094/"  # DNS of Microservice B in Kubernetes
      # volumes:
      # - name: bff-volume-config
      #    configMap:
      #     name: bff-configmap
      #   volumeMounts:
      #   - name: bff-volume-config
      #     mountPath: /app/config/appsettings.json
      #     subPath: appsettings.json 
        ports:
        - containerPort:  8080
          name:  bff-port
---
      apiVersion: v1
      kind: Service
      metadata:
        name: bff-svc
        namespace: efsoft
      spec:
        selector:
          app: efsoft-bff
        type: LoadBalancer
        ports:
        - name: bff-port
          protocol: TCP
          port: 8093
          targetPort: 8080
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: bff-configmap
# data:
#   appsettings.json: |
#     {
#       "CustomersService": {
#         "CustomersServiceBaseAddress": "https://localhost:7244",
#         "GetCustomerEndpoint": "api/customer/",
#         "GetCustomersEndpoint": "api/customer/",
#         "PostCustomerEndpoint": "api/customer/",
#         "PutCustomerEndpoint": "api/customer/",
#         "DeleteCustomerEndpoint": "api/customer/"
#       },
      
#       "JwtSecret": "cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ",

#       "Logging": {
#         "LogLevel": {
#           "Default": "Information",
#           "Microsoft": "Warning",
#           "Microsoft.Hosting.Lifetime": "Information"
#         }
#       }
#     }