# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efsoft-bff-deployment
  labels:
    app: efsoft
spec:
  replicas: 3
  selector:
    matchLabels:
      app: efsoft
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: efsoft_bff
      labels:
        env: prod
        app: efsoft
        app.kubernetes.io/name: efsoft
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: bff-pod
        image: emilfilip/efsoft_bff:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-web-api
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: bff-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: efsoft
  ports:
  - name: bff-port
    port: 8085
    targetPort: 80
    protocol: TCP